Vagrant.configure(2) do |config|
  config.vm.box = "phase2/centos-7"

config.vm.provider "virtualbox" do |vb|
  vb.customize ["modifyvm", :id, "--memory", 1024]
  vb.customize ["modifyvm", :id, "--cpus", 1]
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
  config.vm.network :private_network, ip: "10.220.220.10"
  config.vm.network :forwarded_port, guest: 80, host: 8881
  config.vm.network :forwarded_port, guest: 443, host: 8443
  config.vm.synced_folder "../public_html","/var/www/html",create:true


end
