---
  - name: check if EPEL is installed
    shell: /usr/bin/rpmquery epel-release
    register: epel_installed
    ignore_errors: true
    changed_when: false
  - name: install EPEL
    yum:
      pkg: epel-release
      state: installed
  - name: clean yum metadata on first run
    shell: /usr/bin/yum clean all
    when: epel_installed|failed
  - name: upgrade all packages on first run
    yum:
      name: '*'
      state: latest
    when: epel_installed|failed
